### ISSUE TITLE
BioCell Column Style Not Available 

### ISSUE THREAD

**Issue by yamankatby** [mohakapt/react-native-js-tableview#3]
I think there is no Column style for the **BioCell** But also when I tried to make it manually it is not accept `flexDirection: 'column'`.

### Is it a Bug

**Comment by heysem-useinsider** [comment]
I don't think it's a bug, it's more like a feature request. I'll work on it asap anyway.
Thanks for reporting.

**Comment by heysem-useinsider** [comment]
Fixed in v1.3.7
