### ISSUE TITLE
How to hide the scroll bar on the table?

### ISSUE THREAD

**Issue by madeinquant** [mohakapt/react-native-js-tableview#7]
This is a beautiful component. To hide the scrollbar of scrollview, the property (showsVerticalScrollIndicator)  should be set as 'false'. However, please comment how to hide the scroll bar in the package "react-native-js-tableview". Thank you.

**Comment by heysem-useinsider** [comment]
You can do it by wrapping the `Table` component with a `ScrollView` and setting `scrollable` prop on the `Table` to `false`.
Tell me if you need an example, I can provide one.
